### PR TITLE
Add github action to build and push container to quay

### PR DESCRIPTION
**Pull request by jamesfalkner**

### CODE REVIEW

**Comment by edeandrea** [comment]
Do we care about building multi-arch images? Or do we only care about amd64?

Also, why creating a separate `src/main/podman/Containerfile` when there is already a `src/main/docker/Dockerfile` and the push could just be done by adding the container-image-podman extension and doing `./mvnw package -Dquarkus.container-image.push=true`?

**Comment by danieloh30** [comment]
AFAIK, James made this for the Summit Connect lab based on the RHEL AI machine that Tony is working on. So I don't think he needs the multi-arch images but just Linux format. Speaking of adding an extra extension, James might not want to change the code/configs but build & push the latest app to the registry :)

**Comment by edeandrea** [comment]
You can still add an extension without modifying the code just for this use case without having to introduce a "mirror" Containerfile, which is something pretty non-standard for Quarkus. 

I can show you how if interested when I get back from PTO. It would remove the need for 2 of the steps in the workflow (the buildah and push steps).

**Comment by danieloh30** [comment]
Agree if the bot requires to pass down a few maven parameters (e.g., container-image.group/name/tag)! In case we need to deploy the app using the OpenShift extension (I was thinking of it in the PE track for the simple deployment not using the DH template), we need to comment out or remove the container-image-podman extension.

Let's keep discussing when you return!

**Pull request merged**
