### PR TITLE
Building and pushing images using container extension

### PR DESCRIPTION
**Pull request by edeandrea**
Removing the manual building & pushing of container images introduced in #50 in favor of using quarkus container image extensions.

### CODE REVIEW

**Comment by danieloh30** [comment]
Looks good to me. I thought you needed to change the properties but you didn't which is better.

**Comment by edeandrea** [comment]
Nope can do it all from the command line

**Comment by edeandrea** [comment]
I saw it's execution failed for some reason. I'll look into why

**Comment by danieloh30** [comment]
Awesome!

**Pull request merged**
