### PR TITLE
Merge main branch, resolve conflicts, minor updates

### PR DESCRIPTION
**Pull request by kdubois**
I merged the main branch so the branches don't diverge too much.

### CODE REVIEW

**Comment by danieloh30** [comment]
@kdubois Failed to build :)

**Comment by edeandrea** [comment]
There's an issue that I haven't been able to figure out.

https://github.com/quarkiverse/quarkus-langchain4j/issues/823

**Comment by edeandrea** [comment]
On CI, we had it set so that it used Ollama instead of OpenAI. The CI sets up an Ollama instance.

**Comment by kdubois** [comment]
Ok thanks, I fixed it to make sure it uses ollama but now it is indeed running into the ubuntu issue you were referring to.

**Comment by danieloh30** [comment]
Yeah it worked before. Maybe @edeandrea can help this out

**Comment by edeandrea** [comment]
Yeah I was chasing it before I left on leave. If you want you can leave it for me to finish chasing when I get back.

**Comment by danieloh30** [comment]
Sure, I will leave it for you. Take your time!

**Comment by danieloh30** [comment]
` jvm-build-test-21` test is failed @kdubois

**Comment by kdubois** [comment]
looks like it failed due to a timeout this time..

**Pull request merged**
