### PR TITLE
Remove blocking

### PR DESCRIPTION
**Pull request by edeandrea**
Depends on #175

@mariofusco This is the re-do of what you did in #183

### CODE REVIEW

**Review by mariofusco — APPROVED** [review]

**Comment by edeandrea** [comment]
@mariofusco I've built something in now that when dependabot does an update, the checks also check that update against the downstream branches in this repo.

The downstream branches are essentially "solution" branches - the end results of what the users do in modules of the workshop. All changes made to `main` automatically flow to these branches without user intervention (unless there are merge conflicts).

I've updated the CI processes to also check and make sure that dependency updates don't cause failures in these other branches, which was the case with the langchain 0.22.0 update. It was fine on `main` but not on one of the other branches.

That won't happen again.

**Comment by edeandrea** [comment]
Hey @mariofusco I updated to the latest Quarkus LangChain4j (`0.23.0.CR1`), but I'm not sure things are working properly? When I look at the logs I see

```
2024-12-13 16:01:01,006 INFO  [org.par.res.ClaimWebsocketChatBot] (vert.x-eventloop-thread-1) Got chat query: ClaimBotQuery[claimId=1, claim=
    On January 2nd, 1955, at around 3:30 PM, a car accident occurred at the intersection of Colima Road and Azusa Avenue in Hill Vallet. The involved parties were Marty McFly, driving a silver Delorean DMC-12 (OUTA-TIME), and Biff Tanner in a blue Type 2 Volkswagen Bus (BIF-RULZ).
    Marty was heading south on Colima Road when Biff failed to stop at the red traffic signal on Asuza Avenue, causing a collision with Marty's vehicle. Both drivers exchanged information and took photos of the accident scene, which included damages to the front driver and passenger side of Marty's Delorean DMC-12 and the front driver's side of Biff's Volkswagen Bus. No injuries were reported.
    Marty has attached necessary documents, such as photos, a police report, and an estimate for repair costs, to his email. He requests prompt attention to the claim and is available at (916) 555-4385 or marty.mcfly@email.com for any additional information or documentation needed.
    , query=Should I approve this claim?, inceptionDate=1954-09-30]
2024-12-13 16:01:01,922 INFO  [com.git.tja.jla.ten.ope.TensorOperationsProvider] (vert.x-eventloop-thread-1) Using Native SIMD Operations (OffHeap)
2024-12-13 16:01:01,930 INFO  [com.git.tja.jla.mod.AbstractModel] (vert.x-eventloop-thread-1) Model type = Q4, Working memory type = F32, Quantized memory type = I8
2024-12-13 16:01:02,186 INFO  [com.git.tja.jla.mod.AbstractModel] (vert.x-eventloop-thread-1) Model type = Q4, Working memory type = F32, Quantized memory type = I8
```

It still shows that the query and jlama is running on the event loop thread? Is that what it should be? Shouldn't it be on an executor/worker thread?

**Comment by mariofusco** [comment]
@edeandrea I don't think that this is running on the event loop thread otherwise you should see tons of warnings (one every 2 seconds) that you're blocking it as it did before.

@geoand @cescoffier can you please confirm?

**Comment by geoand** [comment]
Yeah, it shouldn't be

**Pull request merged**
